### ISSUE TITLE
Postgres: authentication method 10 not supported

### ISSUE THREAD

**Issue by mvelazc0** [fireeye/PwnAuth#21]
Hi, getting the following error when running setup.sh

Successfully built 9eaf079b62d5
Successfully tagged pwnauth_web:latest
pwnauth_db_1 is up-to-date
pwnauth_web_1 is up-to-date
Starting pwnauth_db_1 ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: authentication method 10 not supported

**Comment by DeveloperOl** [comment]
using postgres 12 docker image fixed the error "authentication method 10 not supported" for me.

**Comment by DaX27104** [comment]
hey could you guide me installing and execute step by step  PwnAuth
